version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
    networks:
      - localnet

  postgres:
    image: postgres:15
    container_name: local-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - localnet

  lambda-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lambda-dev
    depends_on:
      - localstack
      - postgres
    volumes:
      - ./:/workspace
      - //./pipe/docker_engine:/var/run/docker.sock
    networks:
      - localnet
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1

networks:
  localnet:
