Resources:
  ConsultarUsuarioFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      CodeUri: target/demo-0.0.1-SNAPSHOT-aws.jar
      Runtime: java17
      Environment:
        Variables:
          MAIN_CLASS: com.example.demo.DemoApplication
          SPRING_CLOUD_FUNCTION_DEFINITION: consultarUsuarioFunction
          AWS_REGION: us-east-1
          DB_SECRET_NAME: my-db-secret
